title: "Sonatype Help"
description: "Sonatype Documentation - Jekyll Migration"
baseurl: "/help-on-jekyll"  # Replace with your repository name
url: "https://hernanortiz.github.io"  # Replace with your GitHub username

theme: just-the-docs
color_scheme: light

# Logo configuration
logo: "/assets/images/portal-logo.png"

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation structure
nav_sort: case_insensitive

# Footer settings
footer_content: "Copyright &copy; Sonatype Inc."

# GitHub Pages / Jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap


# Just the Docs specific configurations
just_the_docs:
  collections:
    docs:
      permalink: "/:collection/:name/"
      output: true


# Files to exclude
exclude:
  - export-html/
  - export-xml/
  - left-menu-structure.json
  - site-structure.json
  - migrate_content.py
  - migrate_images.py
  - node_modules/
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - script/
  - LICENSE.txt
  - lib/
  - bin/
  - README.md
  - Rakefile

# Include assets directory
include:
  - assets/

# Markdown settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"